### ISSUE TITLE
Add option for creating rpm from current project state rather than last commit hash

### ISSUE THREAD

**Issue by jwlodek** [NSLS2/git-rpm-tools#1]
Currently, to test an RPM w/ after editing files, you need to commit all changes before running `make rpm`. While for production builds this makes sense to me, during development it can be a bit annoying to have to keep making commits for single line typos to be able to generate a new rpm w/ the fix. This also then clogs up the git history with tiny, one line commits.

I suggest we come up with an alternate solution w/ a different make target, i.e. `make dev-rpm` or something, so that when making changes we can quickly iterate and test the new rpm version w/ the changes without committing.

**Comment by aderbenev** [comment]
The behavior comes from how `git archive` works, and it requires a branch from which the archive is created. I remember that I opted to retain that behavior to make the building less error-prone, as it includes a cognizant step (the commit) before the RPM is made.

That said, I like the idea of keeping the default mechanism as it is while also providing a more convenient development route. It looks like there are two ways to make this happen - use `git stash create` and use the result as a "temporary branch", or use `git archive --add-file` - but that option seemingly has no option to just include all files at once.

Because there is already support for specifying the target branch, you can get the desired behavior now with:
```
git-rpm-tools -b `git stash create` bb
```
